# Generated by Django 4.2.7 on 2026-05-28 16:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'Utility'), ('TRAVEL', 'Travel')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PARSING', 'Parsing'), ('PARSED', 'Parsed'), ('FAILED', 'Failed'), ('PARTIALLY_PARSED', 'Partially Parsed')], default='UPLOADED', max_length=20)),
                ('uploaded_file', models.FileField(upload_to='uploads/')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(default='', max_length=255)),
                ('total_rows', models.IntegerField(default=0)),
                ('parsed_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('suspicious_rows', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='esg.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('source_type', models.CharField(max_length=20)),
                ('raw_payload', models.JSONField()),
                ('hash', models.CharField(max_length=64)),
                ('parse_status', models.CharField(choices=[('PARSED', 'Parsed'), ('FAILED', 'Failed')], max_length=10)),
                ('parse_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingestion_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='esg.ingestionjob')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='esg.tenant')),
            ],
            options={
                'unique_together': {('ingestion_job', 'row_number')},
            },
        ),
        migrations.AddField(
            model_name='ingestionjob',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='esg.tenant'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='esg.tenant'),
        ),
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', max_length=20)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, max_length=255, null=True)),
                ('scope', models.CharField(blank=True, choices=[('SCOPE_1', 'Scope 1'), ('SCOPE_2', 'Scope 2'), ('SCOPE_3', 'Scope 3')], max_length=10, null=True)),
                ('category', models.CharField(blank=True, choices=[('FUEL_COMBUSTION', 'Fuel Combustion'), ('ELECTRICITY', 'Electricity'), ('PROCUREMENT', 'Procurement'), ('FLIGHT', 'Flight'), ('HOTEL', 'Hotel'), ('GROUND', 'Ground')], max_length=20, null=True)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('unit_original', models.CharField(blank=True, max_length=30, null=True)),
                ('quantity_normalized', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('unit_normalized', models.CharField(blank=True, max_length=30, null=True)),
                ('facility_id', models.CharField(blank=True, max_length=100, null=True)),
                ('facility_name', models.CharField(blank=True, max_length=255, null=True)),
                ('meter_id', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cost_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('travel_mode', models.CharField(blank=True, max_length=20, null=True)),
                ('origin', models.CharField(blank=True, max_length=10, null=True)),
                ('destination', models.CharField(blank=True, max_length=10, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cabin_class', models.CharField(blank=True, max_length=50, null=True)),
                ('nights', models.IntegerField(blank=True, null=True)),
                ('material_group', models.CharField(blank=True, max_length=100, null=True)),
                ('spend_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('spend_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('flags', models.JSONField(default=list)),
                ('edited_fields', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingestion_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to='esg.ingestionjob')),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_record', to='esg.rawrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to='esg.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityEditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edited_by', models.CharField(max_length=255)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('activity_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='esg.activityrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='esg.tenant')),
            ],
        ),
    ]
